---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kevin.
--- DateTime: 2022/11/27 09:37
---

-- 1.1优惠券ID
local voucherId = ARGV[1]
-- 1.2 用户ID
local userId = ARGV[2]
-- 1.3 订单ID
local orderId = ARGV[3]

-- 2.1 库存key ".." 是lua的字符串拼接符号
local stockKey = 'seckill:stock:' .. voucherId
-- 这里的orderkey存储的是这个优惠券购买的用户列表，和数据库的order表的ID不一样，但是这个redis的设计就像一个key对应了数据库的一张表
local orderKey = 'seckill:order:' .. voucherId

-- 判断库存是否充足，redis.call返回的字符串类型，要先转换成数值类型再判断大小
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2.库存不足，返回1
    return 1
end

-- 判断一人一单问题
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 3.3.存在，说明是重复下单，返回2
    return 2
end

-- 扣库存
redis.call('incrby', stockKey, -1)
-- 保存用户ID到order的key中
redis.call('sadd', orderKey, userId)
-- 发送消息到队列中（redis的消息队列持久化啥的会有问题吧，还是消息队列的框架才能完美解决）
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0